"""Builds the whole VHDL file text for one module and owns its layout.

Fixed structure, in order: the SLAC license comment block, a generated-file
banner naming the source `.v` file and the transpiler version with no
wall-clock timestamp anywhere (so a re-run at a fixed tool version is
byte-identical by construction), the fixed library preamble emitted
identically in every file, the entity (generic and port clauses aligned by
construction, never by shelling out to `vsg`), the architecture with its
mandatory blank lines, and `end rtl;`.

Generic typing rule, locked here because it decides whether the
equivalence harness can drive the entity at all: a Verilog `parameter`
becomes an integer-typed VHDL generic named by uppercasing the parameter
name and appending `_G`. A parameter used as a width bound becomes
`positive`; a parameter used as a value becomes `natural`, converted at
its use site with `toSlv(<GENERIC>, <width>)` wherever a vector context
needs it. Never emits a `TPD_G` generic or any delay clause on any
assignment: these entities are compared cycle by cycle against their
Verilog originals, and any output delay breaks bit-exactness by
construction.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from . import initializers as _initializers
from . import instantiate as _instantiate
from . import stmt as _stmt
from . import width as _width
from .mangle import NameMap

__all__ = ["emit_vhdl"]

INDENT = "   "

_SLAC_HEADER = (
    "-------------------------------------------------------------------------------\n"
    "-- This file is part of 'SLAC Firmware Standard Library'.\n"
    "-- It is subject to the license terms in the LICENSE.txt file found in the\n"
    "-- top-level directory of this distribution and at:\n"
    "--    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.\n"
    "-- No part of 'SLAC Firmware Standard Library', including this file,\n"
    "-- may be copied, modified, propagated, or distributed except according to\n"
    "-- the terms contained in the LICENSE.txt file.\n"
    "-------------------------------------------------------------------------------"
)

_LIBRARY_PREAMBLE = (
    "library ieee;\n"
    "use ieee.std_logic_1164.all;\n"
    "use ieee.numeric_std.all;\n"
    "\n"
    "library surf;\n"
    "use surf.StdRtlPkg.all;"
)


@dataclass
class _EmitContext:
    path: Path
    name_map: NameMap
    generic_name: dict
    param_kind: dict
    param_names: set
    signal_size: dict = field(default_factory=dict)

    def is_param(self, name: str) -> bool:
        return name in self.param_names

    def name_for(self, name: str) -> str:
        try:
            return self.name_map.signal(name)
        except KeyError:
            return self.name_map.port(name)

    def target_width_for(self, name: str) -> str | None:
        return self.signal_size.get(name)


def emit_vhdl(module_ir, tool_version: str = "0.1.0") -> str:
    name_map = NameMap.build(module_ir)
    generic_name = {param.name: f"{param.name.upper()}_G" for param in module_ir.params}
    param_kind = {param.name: _param_kind(param.name, module_ir) for param in module_ir.params}

    ctx = _EmitContext(
        path=module_ir.source_path,
        name_map=name_map,
        generic_name=generic_name,
        param_kind=param_kind,
        param_names={param.name for param in module_ir.params},
    )
    for port in module_ir.ports:
        if not port.is_scalar:
            ctx.signal_size[port.name] = _width.symbolic_size(port.msb_expr, port.lsb_expr)
    for signal in module_ir.signals:
        if not signal.is_scalar:
            ctx.signal_size[signal.name] = _width.symbolic_size(signal.msb_expr, signal.lsb_expr)

    entity_lines = _render_entity(module_ir, param_kind, generic_name)
    declarative_lines, used_helpers = _render_declarations(module_ir, ctx)
    body_lines = _render_body(module_ir, ctx, used_helpers)

    lines: list[str] = []
    lines.append(_SLAC_HEADER)
    lines.append(_generated_banner(module_ir.source_path, tool_version))
    lines.append("")
    lines.append(_LIBRARY_PREAMBLE)
    lines.append("")
    lines.extend(entity_lines)
    lines.append("")
    lines.append(f"architecture rtl of {module_ir.name} is")
    lines.append("")
    lines.extend(declarative_lines)
    lines.append("")
    lines.append("begin")
    lines.append("")
    lines.extend(body_lines)
    lines.append("")
    lines.append("end rtl;")

    text = "\n".join(line.rstrip() for line in lines)
    return text + "\n"


def _generated_banner(source_path: Path, tool_version: str) -> str:
    return (
        "-------------------------------------------------------------------------------\n"
        f"-- Generated by bsc2vhdl {tool_version} from {source_path.name}.\n"
        "-- Do not hand-edit: re-run the transpiler to regenerate this file.\n"
        "-------------------------------------------------------------------------------"
    )


def _param_kind(param_name: str, module_ir) -> str:
    width_texts: list[str] = []
    for port in module_ir.ports:
        if port.msb_expr:
            width_texts.append(port.msb_expr)
        if port.lsb_expr:
            width_texts.append(port.lsb_expr)
    for signal in module_ir.signals:
        if signal.msb_expr:
            width_texts.append(signal.msb_expr)
        if signal.lsb_expr:
            width_texts.append(signal.lsb_expr)
    pattern = re.compile(rf"\b{re.escape(param_name)}\b")
    return "positive" if any(pattern.search(text) for text in width_texts) else "natural"


def _vector_type(msb_expr, lsb_expr, is_scalar) -> str:
    if is_scalar or msb_expr is None:
        return "sl"
    return f"slv({_width.symbolic(msb_expr)} downto {_width.symbolic(lsb_expr)})"


def _render_entity(module_ir, param_kind, generic_name) -> list[str]:
    lines = [f"entity {module_ir.name} is"]
    lines.extend(_render_generic_clause(module_ir, param_kind, generic_name))
    lines.extend(_render_port_clause(module_ir))
    lines.append(f"end {module_ir.name};")
    return lines


def _render_generic_clause(module_ir, param_kind, generic_name) -> list[str]:
    entries = [
        (generic_name[param.name], param_kind[param.name], str(param.default_value))
        for param in module_ir.params
    ]
    max_name = max(len(name) for name, _, _ in entries)
    max_type = max(len(kind) for _, kind, _ in entries)
    lines = [f"{INDENT}generic ("]
    for index, (name, kind, default) in enumerate(entries):
        terminator = ");" if index == len(entries) - 1 else ";"
        lines.append(
            f"{INDENT * 2}{name.ljust(max_name + 1)}: {kind.ljust(max_type + 1)}:= {default}{terminator}"
        )
    return lines


def _render_port_clause(module_ir) -> list[str]:
    ins = [port for port in module_ir.ports if port.direction == "in"]
    outs = [port for port in module_ir.ports if port.direction == "out"]
    entries = [
        (port.name, port.direction, _vector_type(port.msb_expr, port.lsb_expr, port.is_scalar))
        for port in ins + outs
    ]
    max_name = max(len(name) for name, _, _ in entries)
    max_dir = max(len(direction) for _, direction, _ in entries)
    lines = [f"{INDENT}port ("]
    for index, (name, direction, type_text) in enumerate(entries):
        terminator = ");" if index == len(entries) - 1 else ";"
        lines.append(
            f"{INDENT * 2}{name.ljust(max_name + 1)}: {direction.ljust(max_dir)} {type_text}{terminator}"
        )
    return lines


def _render_declarations(module_ir, ctx) -> tuple[list[str], set[str]]:
    used_helpers: set[str] = set()
    signal_lines: list[str] = []
    for signal in module_ir.signals:
        vhdl_name = ctx.name_map.signal(signal.name)
        type_text = _vector_type(signal.msb_expr, signal.lsb_expr, signal.is_scalar)
        default = _initializers.initializer_for(signal, module_ir.initials, ctx)
        if default is not None and "bsvAltInit(" in default:
            used_helpers.add("bsvAltInit")
        suffix = f" := {default}" if default is not None else ""
        signal_lines.append(f"{INDENT}signal {vhdl_name} : {type_text}{suffix};")

    helper_lines = _initializers.helper_functions(used_helpers)
    lines: list[str] = []
    if helper_lines:
        lines.extend(helper_lines)
        lines.append("")
    lines.extend(signal_lines)
    return lines, used_helpers


def _render_body(module_ir, ctx, used_helpers) -> list[str]:
    lines: list[str] = []
    lines.extend(_instantiate.component_declarations(module_ir, ctx))
    for always_block in module_ir.always_blocks:
        lines.extend(_render_process(always_block, ctx))

    signal_by_original = {signal.name: signal for signal in module_ir.signals}
    driving_lines = [
        f"{INDENT}{port.name} <= {ctx.name_for(port.name)};"
        for port in module_ir.ports
        if port.direction == "out" and port.name in signal_by_original
    ]
    if driving_lines and lines:
        lines.append("")
    lines.extend(driving_lines)

    return lines


def _render_process(always_node, ctx) -> list[str]:
    clock_name = always_node.sens_list.list[0].sig.name
    lines = [
        f"{INDENT}process ({clock_name}) is",
        f"{INDENT}begin",
        f"{INDENT * 2}if rising_edge({clock_name}) then",
    ]
    lines.extend(_stmt.render_statement(always_node.statement, ctx, indent=3))
    lines.append(f"{INDENT * 2}end if;")
    lines.append(f"{INDENT}end process;")
    return lines
