-------------------------------------------------------------------------------
-- This file is part of 'SLAC Firmware Standard Library'.
-- It is subject to the license terms in the LICENSE.txt file found in the
-- top-level directory of this distribution and at:
--    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
-- No part of 'SLAC Firmware Standard Library', including this file,
-- may be copied, modified, propagated, or distributed except according to
-- the terms contained in the LICENSE.txt file.
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-- Generated by bsc2vhdl 0.1.0 from RegN.v.
-- Do not hand-edit: re-run the transpiler to regenerate this file.
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library surf;
use surf.StdRtlPkg.all;

entity RegN is
   generic (
      WIDTH_G : positive := 1;
      INIT_G  : natural  := 0);
   port (
      CLK   : in  sl;
      RST   : in  sl;
      D_IN  : in  slv(WIDTH_G-1 downto 0);
      EN    : in  sl;
      Q_OUT : out slv(WIDTH_G-1 downto 0));
end RegN;

architecture rtl of RegN is

   function bsvAltInit (size : positive) return slv is
      variable ret : slv(size-1 downto 0);
   begin
      for i in 0 to size-1 loop
         if (i mod 2) = 1 then
            ret(i) := '1';
         else
            ret(i) := '0';
         end if;
      end loop;
      return ret;
   end function bsvAltInit;

   signal qOut : slv(WIDTH_G-1 downto 0) := bsvAltInit(WIDTH_G);

begin

   process (CLK) is
   begin
      if rising_edge(CLK) then
         if (RST = '0') then
            qOut <= toSlv(INIT_G, WIDTH_G);
         elsif (EN = '1') then
            qOut <= D_IN;
         end if;
      end if;
   end process;

   Q_OUT <= qOut;

end rtl;
